CREATE TABLE expenses (
  id CHAR(36) NOT NULL,
  owner_subject VARCHAR(128) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  service_date DATE NOT NULL,
  merchant_provider VARCHAR(255) NOT NULL,
  recipients VARCHAR(255) NOT NULL,
  expense_category VARCHAR(32) NOT NULL,
  status VARCHAR(64) NOT NULL,
  plan_name VARCHAR(255) NULL,
  expense_type VARCHAR(255) NULL,
  expense_sub_type VARCHAR(255) NULL,
  eob_number VARCHAR(255) NULL,
  paid_amount DECIMAL(12,2) NULL,
  denied_amount DECIMAL(12,2) NULL,
  payee_name VARCHAR(255) NULL,
  payee_account_number VARCHAR(255) NULL,
  payee_address_line_1 VARCHAR(255) NULL,
  payee_address_line_2 VARCHAR(255) NULL,
  payee_city VARCHAR(255) NULL,
  payee_state VARCHAR(32) NULL,
  payee_zip_code VARCHAR(32) NULL,
  comment TEXT NULL,
  claim_number VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_expenses_owner_date (owner_subject, service_date),
  INDEX idx_expenses_owner_category (owner_subject, expense_category)
);

